# Generated by Django 4.2.26 on 2025-11-30 18:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('affiliation', models.CharField(blank=True, max_length=300, verbose_name='Afiliação')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('abstract', models.TextField(blank=True, verbose_name='Resumo')),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano')),
                ('venue', models.CharField(blank=True, max_length=300, verbose_name='Venue/Conferência')),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='papers/', verbose_name='Arquivo PDF')),
                ('priority', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_LEITURA', 'Em leitura'), ('LIDO', 'Lido'), ('REVISANDO', 'Revisando')], default='NAO_INICIADO', max_length=15, verbose_name='Status')),
                ('progress_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progresso (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('authors', models.ManyToManyField(blank=True, related_name='papers', to='core.author', verbose_name='Autores')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração (minutos)')),
                ('quick_notes', models.TextField(blank=True, verbose_name='Notas rápidas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='core.paper', verbose_name='Paper')),
            ],
            options={
                'verbose_name': 'Sessão de leitura',
                'verbose_name_plural': 'Sessões de leitura',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Score')),
                ('last_recommended_at', models.DateTimeField(blank=True, null=True, verbose_name='Última recomendação')),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_entry', to='core.paper', verbose_name='Paper')),
            ],
            options={
                'verbose_name': 'Entrada de ranking',
                'verbose_name_plural': 'Entradas de ranking',
                'ordering': ['-score'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='papers', to='core.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('note_type', models.CharField(choices=[('INSIGHT', 'Insight'), ('CRITICA', 'Crítica'), ('DUVIDA', 'Dúvida'), ('CITACAO', 'Citação'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.paper', verbose_name='Paper')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('code_repository_url', models.URLField(blank=True, verbose_name='URL do repositório')),
                ('dataset_description', models.TextField(blank=True, verbose_name='Descrição do dataset')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_EXECUCAO', 'Em execução'), ('CONCLUIDO', 'Concluído'), ('ABORTADO', 'Abortado')], default='PLANEJADO', max_length=15, verbose_name='Status')),
                ('main_results', models.TextField(blank=True, verbose_name='Principais resultados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('papers', models.ManyToManyField(blank=True, related_name='experiments', to='core.paper', verbose_name='Papers relacionados')),
            ],
            options={
                'verbose_name': 'Experimento',
                'verbose_name_plural': 'Experimentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
