# Generated by Django 3.2.25 on 2025-12-03 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Páginas'),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='pages_read',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Páginas lidas'),
        ),
    ]
